name: Build and Push Docker Image

on:
  push:
    branches:
      - docker   # run only on docker branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/neosaas
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/neosaas
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
